<a href="https://colab.research.google.com/github/Vijay8185/Assignments/blob/main/Numpy_Assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
a = np.random.randn(4,4)

In [6]:
a

array([[-0.74789164, -0.21159242, -0.02605443,  0.91506352],
       [ 0.30173713,  0.67998034, -0.45460897,  0.45847381],
       [ 3.38612264,  0.9280185 ,  0.66630309, -0.80235304],
       [-0.06153676,  0.97151226,  0.92292795,  0.0073727 ]])

# Assignment
(A)

In [7]:
a

array([[-0.74789164, -0.21159242, -0.02605443,  0.91506352],
       [ 0.30173713,  0.67998034, -0.45460897,  0.45847381],
       [ 3.38612264,  0.9280185 ,  0.66630309, -0.80235304],
       [-0.06153676,  0.97151226,  0.92292795,  0.0073727 ]])

In [8]:
# row no.3 & row.4
a[2::1]

array([[ 3.38612264,  0.9280185 ,  0.66630309, -0.80235304],
       [-0.06153676,  0.97151226,  0.92292795,  0.0073727 ]])

In [9]:
# middle two rows i.e. row no.2 & row no.3
a = np.random.randn(4,4)

In [10]:
a

array([[-1.11095902, -1.80368128, -0.8754608 ,  0.41675453],
       [ 0.88033695, -0.52600389, -1.08331249, -0.61914926],
       [ 0.05428123, -0.27179897, -0.25238306, -0.30980076],
       [-1.19012593, -0.72546048, -0.14041315,  0.30744875]])

In [11]:
a = a[[1,2]]

In [12]:
a

array([[ 0.88033695, -0.52600389, -1.08331249, -0.61914926],
       [ 0.05428123, -0.27179897, -0.25238306, -0.30980076]])

In [13]:
# 1st & last row
a = np.random.randn(4,4)

In [14]:
a

array([[ 0.72789463,  1.4854577 ,  0.27679745, -0.82354056],
       [-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.82516145, -2.30527999, -0.19362362,  0.2329293 ],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

In [15]:
a[::3]

array([[ 0.72789463,  1.4854577 ,  0.27679745, -0.82354056],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

In [16]:
# 2nd & 4th row
a[1::2]

array([[-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

In [17]:
# last 3 rows
a[1::]

array([[-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.82516145, -2.30527999, -0.19362362,  0.2329293 ],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

# Assignment
(B)

In [18]:
# access corner elements
a

array([[ 0.72789463,  1.4854577 ,  0.27679745, -0.82354056],
       [-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.82516145, -2.30527999, -0.19362362,  0.2329293 ],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

In [19]:
a[[0,-1]][:,[0,-1]]

array([[ 0.72789463, -0.82354056],
       [ 0.44556296,  0.30718107]])

In [26]:
# diagonal elements
np.diag(a)

array([ 0.72789463,  0.41719471, -0.19362362,  0.30718107])

In [30]:
# access middle 2 columns and all rows
a[:,1:3]

array([[ 1.4854577 ,  0.27679745],
       [ 0.41719471, -0.54531758],
       [-2.30527999, -0.19362362],
       [-0.24262215, -1.16548727]])

In [31]:
# access last 2 rows and its first 2 values from each row
a

array([[ 0.72789463,  1.4854577 ,  0.27679745, -0.82354056],
       [-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.82516145, -2.30527999, -0.19362362,  0.2329293 ],
       [ 0.44556296, -0.24262215, -1.16548727,  0.30718107]])

In [62]:
a[2,0],a[3,0]

(0.8251614469302297, 0.445562960980659)

In [64]:
# reverse rows and columns as well
a[::-1] # reverse rows

array([[ 0.44556296, -0.24262215, -1.16548727,  0.30718107],
       [ 0.82516145, -2.30527999, -0.19362362,  0.2329293 ],
       [-0.08000222,  0.41719471, -0.54531758,  1.14373897],
       [ 0.72789463,  1.4854577 ,  0.27679745, -0.82354056]])

In [67]:
a[:,::-1] # reverse columns

array([[-0.82354056,  0.27679745,  1.4854577 ,  0.72789463],
       [ 1.14373897, -0.54531758,  0.41719471, -0.08000222],
       [ 0.2329293 , -0.19362362, -2.30527999,  0.82516145],
       [ 0.30718107, -1.16548727, -0.24262215,  0.44556296]])

In [71]:
# reshape() vs resize()
# reshape() : the reshape() returns changed array does not changes the original array.
# resize() : the resize() method returns nothing and directly changes the original array.
a = np.random.randn(4,4)

In [72]:
a

array([[-1.21880629, -0.59415676, -0.27692836,  1.25485509],
       [ 0.89070716,  1.08530803, -0.45760746, -0.70554781],
       [ 0.48262003,  1.80541007, -0.01236325, -0.30400309],
       [-1.24055653, -1.50318181,  0.86316236,  0.19652657]])

In [76]:
a.reshape(2,4,2) # reshaped array

array([[[-1.21880629, -0.59415676],
        [-0.27692836,  1.25485509],
        [ 0.89070716,  1.08530803],
        [-0.45760746, -0.70554781]],

       [[ 0.48262003,  1.80541007],
        [-0.01236325, -0.30400309],
        [-1.24055653, -1.50318181],
        [ 0.86316236,  0.19652657]]])

In [77]:
a # oringinal stays as it is

array([[-1.21880629, -0.59415676, -0.27692836,  1.25485509],
       [ 0.89070716,  1.08530803, -0.45760746, -0.70554781],
       [ 0.48262003,  1.80541007, -0.01236325, -0.30400309],
       [-1.24055653, -1.50318181,  0.86316236,  0.19652657]])

In [78]:
a.resize(2,4,2)

In [79]:
a # resized array

array([[[-1.21880629, -0.59415676],
        [-0.27692836,  1.25485509],
        [ 0.89070716,  1.08530803],
        [-0.45760746, -0.70554781]],

       [[ 0.48262003,  1.80541007],
        [-0.01236325, -0.30400309],
        [-1.24055653, -1.50318181],
        [ 0.86316236,  0.19652657]]])

In [80]:
a # original array size has been changed permanently.

array([[[-1.21880629, -0.59415676],
        [-0.27692836,  1.25485509],
        [ 0.89070716,  1.08530803],
        [-0.45760746, -0.70554781]],

       [[ 0.48262003,  1.80541007],
        [-0.01236325, -0.30400309],
        [-1.24055653, -1.50318181],
        [ 0.86316236,  0.19652657]]])